-   repo: local
    hooks:
    -   id: pre_commit_hook	
        name: pre_commit_hook
        entry: dyc diff
        verbose: true
        language: python
        pass_filenames: false
        always_run: true
